# Generated by Django 5.2.8 on 2025-11-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='device',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
