# Generated by Django 5.2.8 on 2025-11-06 11:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPSEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPSPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('velocidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('battery', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posiciones', to='gps.device')),
                ('id_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gps.gpsevent')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posiciones', to=settings.AUTH_USER_MODEL)),
                ('id_ruta', models.ForeignKey(blank=True, db_column='id_ruta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posiciones', to='gps.route')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='ultima_posicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gps.gpsposition'),
        ),
        migrations.AddIndex(
            model_name='gpsposition',
            index=models.Index(fields=['fecha_hora'], name='gps_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsposition',
            index=models.Index(fields=['latitud'], name='gps_lat_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsposition',
            index=models.Index(fields=['longitud'], name='gps_lng_idx'),
        ),
    ]
