# Generated by Django 5.2.8 on 2025-11-07 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_alter_bus_ruta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parada',
        ),
    ]
