# Generated by Django 5.2.8 on 2025-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_delete_parada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='ruta',
        ),
        migrations.AddField(
            model_name='ruta',
            name='buses',
            field=models.ManyToManyField(blank=True, related_name='rutas', to='rutas.bus', verbose_name='Buses asignados'),
        ),
    ]
