# Generated by Django 5.2.8 on 2025-11-06 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0002_alter_bus_ruta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('velocidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posiciones', to='rutas.ruta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posiciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GPS Posición',
                'verbose_name_plural': 'GPS Posiciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='EventoDesvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_desvio', models.CharField(max_length=100)),
                ('estado', models.CharField(default='abierto', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='rutas.ruta')),
                ('posicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='gps.gpsposicion')),
            ],
            options={
                'verbose_name': 'Evento Desvío',
                'verbose_name_plural': 'Eventos Desvío',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
