# Generated by Django 5.2.8 on 2025-11-07 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0002_alter_bus_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la parada')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('coordenada_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('coordenada_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('orden', models.IntegerField(default=0, help_text='Orden de la parada en la secuencia de la ruta', verbose_name='Orden en la ruta')),
                ('activa', models.BooleanField(default=True, verbose_name='Parada activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_gestionadas', to='rutas.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['ruta', 'orden', 'nombre'],
                'indexes': [models.Index(fields=['ruta', 'orden'], name='paradas_par_ruta_id_d20b97_idx'), models.Index(fields=['coordenada_lat', 'coordenada_lng'], name='paradas_par_coorden_fa1fdb_idx')],
            },
        ),
    ]
