# Generated by Django 5.2.7 on 2025-11-04 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeEspera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruta', models.UUIDField(blank=True, help_text='UUID de la ruta asociada', null=True)),
                ('posicion', models.PositiveIntegerField(help_text='Posición actual en la lista de espera')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('PASO_A_RESERVA', 'Pasó a Reserva'), ('CANCELADO', 'Cancelado')], default='EN_ESPERA', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_espera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
                'ordering': ['posicion', 'fecha_inscripcion'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'ruta'), name='unique_lista_espera_por_usuario_y_ruta')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruta', models.UUIDField(blank=True, help_text='UUID de la ruta asignada', null=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='RESERVADO', max_length=15)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'ruta'), name='unique_reserva_por_usuario_y_ruta')],
            },
        ),
    ]
