# Generated by Django 5.2.7 on 2025-11-06 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0002_alter_bus_ruta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('EN_ESPERA', 'En Espera'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='RESERVADO', max_length=20)),
                ('posicion_espera', models.PositiveIntegerField(blank=True, help_text='Posición en la lista de espera si aplica', null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('ruta', models.ForeignKey(help_text='Ruta asociada a la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas_cupo', to='rutas.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_cupo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva de Cupo',
                'verbose_name_plural': 'Reservas de Cupos',
                'ordering': ['-fecha_reserva'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'ruta'), name='unique_reserva_cupo_por_usuario_y_ruta')],
            },
        ),
    ]
